"""Rewrite Air Law distractors so options are close in length and meaning.

Each entry: id -> [correct, distractor, distractor, distractor].
Answer positions are reshuffled so A-D are evenly distributed.
"""
import json
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BANK = ROOT / "data" / "010_air_law_question_bank.json"

QUESTION_EDITS = {
    17: "Which convention is identified in the syllabus as the modern framework for international carriage by air?",
}

C = {
    1: ["Chicago Convention", "Warsaw Convention", "Tokyo Convention", "Paris Convention"],
    2: ["7 December 1944", "4 April 1947", "1 November 1944", "7 December 1947"],
    3: ["State sovereignty over airspace", "Freedom of the high seas applied to airspace", "Common ownership of international airspace", "Unrestricted innocent passage for all aircraft"],
    4: ["Doc 7300/9", "Doc 4444", "Doc 8168", "Doc 9859"],
    5: ["Promote safe and orderly development of international civil aviation", "Set fares and ticketing rules for international air carriers", "Promote the commercial interests of member airlines worldwide", "Regulate domestic air transport within each Contracting State"],
    6: ["Provide an internationally harmonised framework for civil aviation", "Replace national aviation legislation with a single ICAO rulebook", "Provide binding commercial rules for international airline pricing", "Provide a harmonised framework for State and military aircraft"],
    7: ["Notify the difference to ICAO", "Obtain prior approval of the difference from IATA", "Withdraw from the Convention for that Annex only", "Request an exemption by vote of the ICAO Assembly"],
    8: ["ICAO", "IATA", "ACI", "IFALPA"],
    9: ["IATA", "ICAO", "ECAC", "IFALPA"],
    10: ["The right to overfly another State without landing", "The right to land in another State for non-traffic purposes", "The right to overfly another State and land to refuel", "The right to carry traffic between two foreign States"],
    11: ["The right to land for non-traffic purposes", "The right to overfly another State without landing", "The right to land and set down traffic from the home State", "The right to land for traffic purposes only"],
    12: ["Carry traffic from the carrier's home State to another State", "Carry traffic from another State back to the carrier's home State", "Carry traffic between two foreign States via the home State", "Carry traffic between two points within another State"],
    13: ["Carry traffic from another State back to the carrier's home State", "Carry traffic from the carrier's home State to another State", "Carry traffic between two foreign States via the home State", "Carry traffic between two points within another State"],
    14: ["Third Freedom", "First Freedom", "Second Freedom", "Both the First and Second Freedoms"],
    15: ["Tokyo Convention 1963", "Hague Convention 1970", "Montreal Convention 1971", "Warsaw Convention 1929"],
    16: ["It is evidence of a contract of carriage", "It is evidence of the carrier's traffic rights on that route", "It waives the carrier's liability for loss of baggage", "It is evidence that the passenger has cleared customs"],
    17: ["Montreal Convention 1999", "Montreal Convention 1971", "Warsaw Convention 1929", "Guadalajara Convention 1961"],
    18: ["ICAO is an intergovernmental organisation; IATA is an airline industry association", "ICAO is an airline industry association; IATA is an intergovernmental organisation", "ICAO and IATA are both intergovernmental bodies with regulatory powers", "ICAO regulates domestic aviation; IATA regulates international aviation"],
    19: ["It implements and oversees the national civil aviation regulatory system", "It drafts ICAO Standards on behalf of the States in its region", "It represents the national airlines as a commercial trade body", "It provides air traffic services only, with no regulatory role"],
    20: ["The State's sovereignty and applicable entry/flight requirements", "The right of innocent passage as applied under the law of the sea", "The First Freedom, which permits overflight without any permission", "The operator's route preference and the fuel plan for the flight"],
    21: ["The appropriate authority of the State of Registry", "The authority of the State of the Operator", "The type certificate holder, on behalf of the State of Registry", "The authority of the State of Design"],
    22: ["To certify that the aircraft meets the applicable airworthiness requirements", "To certify that the aircraft is entered on the national register", "To certify that the operator holds a valid AOC for the aircraft", "To certify that the aircraft is adequately insured for operation"],
    23: ["Annex 8", "Annex 6", "Annex 7", "Annex 1"],
    24: ["Annex 7", "Annex 8", "Annex 9", "Annex 6"],
    25: ["The State in which the aircraft is registered", "The State in which the operator is based", "The State in which the aircraft was designed", "The State in whose territory the aircraft is operating"],
    26: ["A mark identifying the individual registered aircraft", "A mark identifying the aircraft type and model", "A mark identifying the operator's airline designator", "A mark showing the aircraft's airworthiness category"],
    27: ["It can affect whether the aircraft may legally and safely be operated", "It only matters once the CofA has formally expired", "It affects the aircraft's registration, not its operation", "It only affects commercial flights, not private flights"],
    28: ["Its continued airworthiness must be assessed under the applicable requirements", "The aircraft may continue operating until the CofA expiry date", "The PIC may accept the damage if the aircraft still handles normally", "The aircraft's registration must be cancelled and re-issued"],
    29: ["Annex 7 — nationality and registration marks", "Annex 8 — nationality and registration marks", "Annex 7 — airworthiness of aircraft", "Annex 6 — personnel licensing"],
    30: ["Registration identifies the aircraft/State; airworthiness addresses compliance for safe operation", "Registration addresses compliance for safe operation; airworthiness identifies the aircraft/State", "Registration and airworthiness are covered by one certificate issued once", "A valid registration automatically confirms that the aircraft is airworthy"],
    31: ["Annex 1 provides international standards; TCAR PEL provides the national licensing framework", "TCAR PEL provides international standards; Annex 1 provides the national licensing framework", "Annex 1 directly licenses pilots; TCAR PEL is guidance material only", "Annex 1 applies to ATPL holders only; TCAR PEL applies to PPL and CPL holders"],
    32: ["Category", "Class", "Type", "Variant"],
    33: ["Class", "Category", "Type", "Group"],
    34: ["Type", "Class", "Category", "Series"],
    35: ["A qualification entered on a licence, such as a class, type or instrument rating", "A separate licence issued for each aircraft category, such as aeroplane", "A medical assessment attached to a licence, such as Class 1 or Class 2", "A qualification entered on a licence, such as a PPL, CPL or ATPL"],
    36: ["ATPL", "CPL", "PPL", "MPL"],
    37: ["FCL.305", "FCL.505", "FCL.205", "FCL.300"],
    38: ["FCL.500", "FCL.505", "FCL.300", "FCL.510"],
    39: ["To qualify the pilot to fly under IFR within the rating's privileges", "To permit flight in IMC without the need for an ATC clearance", "To replace the need for a type rating on complex aircraft", "To allow the pilot to fly under VFR at night only"],
    40: ["Dual instruction time", "Flight duty period", "Rest period", "Standby duty time"],
    41: ["Student Pilot-in-Command", "Supervised Pilot-in-Command", "Single-Pilot Instrument Certificate", "Solo Pilot-in-Command"],
    42: ["Instrument rating", "Multi-crew pilot licence", "Light aircraft pilot licence", "Commercial pilot licence"],
    43: ["To demonstrate continued competence for the relevant privilege/rating", "To demonstrate continued medical fitness for the relevant licence", "To assess the aircraft's continued airworthiness before flight", "To issue an initial licence to a student pilot"],
    44: ["Revalidation extends validity before expiry; renewal restores it after expiry", "Renewal extends validity before expiry; revalidation restores it after expiry", "Revalidation and renewal are identical terms used interchangeably", "Revalidation applies to licences only; renewal applies to medicals only"],
    45: ["Decrease in medical fitness", "Aircraft noise certification", "Cabin crew training records", "Aircraft registration marks"],
    46: ["Follow the medical rules and not exercise privileges contrary to them", "Continue flying until the next scheduled medical examination", "Continue flying provided a second pilot is on board", "Self-assess fitness and fly only if feeling well enough"],
    47: ["Certificate of Airworthiness", "Class 1 medical certificate", "Flight crew licence", "Type rating endorsement"],
    48: ["Because exercising a privilege depends on the licence, rating and conditions", "Because holding the licence automatically includes every rating", "Because a rating can still be exercised after the licence has lapsed", "Because only the rating, not the licence, requires a valid medical"],
    49: ["Annex 1", "Annex 2", "Annex 6", "Annex 11"],
    50: ["Annex 2", "Annex 11", "Annex 1", "Annex 6"],
    51: ["To reduce the risk of collision through standardised responsibilities and actions", "To give ATC sole responsibility for separating all traffic", "To give larger aircraft priority over smaller aircraft in all cases", "To reduce ATC workload by removing the need for clearances"],
    52: ["Each should alter heading to the right", "Each should alter heading to the left", "The faster aircraft should climb and the slower descend", "The aircraft on the left should give way by turning right"],
    53: ["The overtaking aircraft", "The aircraft being overtaken", "The larger or heavier aircraft", "The aircraft at the lower altitude"],
    54: ["The aircraft on the right", "The aircraft on the left", "The faster of the two aircraft", "The aircraft that is climbing"],
    55: ["Retain responsibility for safe operation, including collision avoidance", "Transfer collision-avoidance responsibility to ATC while under control", "Follow ATC instructions only; separation is no longer the PIC's concern", "Retain responsibility for navigation only, while ATC handles collision avoidance"],
    56: ["Operation in applicable VMC and VFR conditions", "Operation in IMC with an ATC clearance", "Operation above any cloud layer at all times", "Operation with an instrument rating, in VMC only"],
    57: ["A VFR flight cleared by ATC to operate within a control zone in conditions below VMC", "A VFR flight conducted outside controlled airspace without any clearance", "An IFR flight that is cleared to proceed visually to the runway", "A VFR flight at night conducted above the transition altitude"],
    58: ["The pilot must hold the applicable qualification and meet the IFR conditions", "An ATC IFR clearance substitutes for the instrument rating", "An instrument rating is only needed in Class A airspace", "A CPL alone permits IFR flight without any further rating"],
    59: ["To provide ATS units with information for flight planning, ATS and alerting", "To obtain an automatic slot and landing permission at destination", "To record the pilot's flight time for licensing purposes", "To replace the need for a pre-flight weather briefing"],
    60: ["The aircraft is intercepted by another aircraft", "The aircraft loses two-way radio communication", "The aircraft is overtaken by a faster aircraft", "The aircraft receives a TCAS traffic advisory"],
    61: ["A clearance authorises an operation under specified conditions; traffic information does not", "Traffic information authorises an operation; a clearance is advisory only", "Both are authorisations and carry exactly the same legal effect", "A clearance transfers collision-avoidance responsibility to ATC; information does not"],
    62: ["Request clarification before acting on the unclear element", "Comply with the most likely interpretation and report later", "Read back the clearance and act on it exactly as heard", "Disregard the unclear element and continue with the flight plan"],
    63: ["Collision avoidance", "Aircraft noise certification", "Airline route licensing", "Pavement strength reporting"],
    64: ["They help show an aircraft's position and relative direction, especially at night", "They replace the need for a transponder when flying at night", "They indicate the aircraft's State of Registry to other traffic", "They illuminate the runway for landing when runway lights fail"],
    65: ["Act in accordance with the applicable Rules of the Air and procedures", "Continue as planned, since the flight was filed as VFR", "Switch to IFR immediately without contacting ATC", "Continue in IMC provided the pilot holds a CPL"],
    66: ["Interception of civil aircraft", "Certification of aircraft noise", "Carriage of dangerous goods", "Licensing of aircraft maintenance engineers"],
    67: ["Pilots retain situational awareness and collision-avoidance responsibilities under ATC", "Because ATC is legally liable for any collision in controlled airspace", "Because collision-avoidance rules only apply when ATC service fails", "Because ATC separation is provided to VFR traffic in all airspace classes"],
    68: ["Right of way establishes priority but does not remove the responsibility to avoid collision", "Right of way removes any need for the aircraft to take avoiding action", "Right of way always belongs to the larger, less manoeuvrable aircraft", "Right of way applies only when both aircraft are receiving ATC service"],
    69: ["Take appropriate action to avoid the collision and communicate with ATC as practicable", "Continue to follow the clearance, since ATC is responsible for separation", "Request permission from ATC before making any avoiding manoeuvre", "Avoid the collision but do not inform ATC, to reduce frequency congestion"],
    70: ["To provide procedures and criteria for instrument flight operations and procedure design", "To provide rules for airline economic regulation and route licensing", "To provide procedures for air traffic management and ATC separation", "To provide standards for aerodrome design and runway markings"],
    71: ["Standard Instrument Departure", "Standard Initial Departure", "Standard IFR Departure", "Standard Instrument Descent"],
    72: ["Standard Instrument Arrival", "Standard Instrument Approach", "Standard Initial Arrival", "Standard Approach and Radar"],
    73: ["A departure permitting specified tracks within published criteria, not one fixed route", "A departure that must follow a single published route to the en-route fix", "A departure flown visually in any direction without obstacle criteria", "A departure permitted only when radar vectors are provided by ATC"],
    74: ["Arrival, initial, intermediate, final, missed approach", "Initial, arrival, intermediate, final, missed approach", "Arrival, intermediate, initial, final, missed approach", "Arrival, initial, final, intermediate, missed approach"],
    75: ["Provide a structured, obstacle-protected path from arrival toward the runway", "Provide the most direct route to the runway without obstacle protection", "Provide ATC with a method of separating traffic on departure", "Provide a structured path for taxiing from the runway to the stand"],
    76: ["MDA/H", "DA/H", "OCA/H", "MSA"],
    77: ["DA/H", "MDA/H", "OCA/H", "MSA"],
    78: ["OCA/H", "MDA/H", "DA/H", "MOCA"],
    79: ["It provides the protected procedure to follow if the approach cannot be completed to landing", "It provides the route to the alternate aerodrome for fuel planning", "It provides an optional visual procedure for circling to land", "It allows the crew to descend below minima to regain visual references"],
    80: ["Initiate the published missed approach procedure", "Continue descent until visual references are acquired", "Level off at minima and continue to the runway threshold", "Begin a visual circling manoeuvre to locate the runway"],
    81: ["To provide a protected pattern for delaying, sequencing or positioning aircraft", "To provide a pattern for descending below the MDA while awaiting visual reference", "To provide a fuel-saving cruise pattern during en-route flight", "To provide a pattern for ATC to separate aircraft laterally on departure"],
    82: ["Direct, parallel and teardrop/offset", "Direct, parallel and procedure turn", "Direct, reverse and teardrop", "Racetrack, parallel and teardrop"],
    83: ["They can take the aircraft outside the protected area and obstacle-clearance assumptions", "They increase fuel burn but have no effect on obstacle clearance", "They may cause the aircraft to exceed its maximum holding speed", "They are only dangerous in VMC, where other traffic is not separated"],
    84: ["To provide defined margins from terrain and obstacles for aircraft on the procedure", "To guarantee terrain clearance even when the aircraft is off the procedure", "To provide separation margins between aircraft on the same procedure", "To provide margins from noise-sensitive areas around the aerodrome"],
    85: ["A pressure setting that makes the altimeter read altitude above mean sea level", "A pressure setting that makes the altimeter read height above the aerodrome", "A standard setting of 1013.25 hPa used to indicate flight levels", "A pressure setting that makes the altimeter read true altitude in all temperatures"],
    86: ["A surface of constant atmospheric pressure related to 1013.25 hPa", "A surface of constant altitude referenced to mean sea level", "A surface of constant pressure referenced to the local QNH", "A surface of constant height above the aerodrome elevation"],
    87: ["The airspace between the transition altitude and the transition level", "The airspace below the transition altitude down to the surface", "The airspace above the transition level up to FL245", "The airspace between the aerodrome elevation and the transition altitude"],
    88: ["To provide protected airspace between parallel final approach paths", "To provide an area in which aircraft may hold between parallel approaches", "To provide airspace for missed approaches from both runways", "To provide a zone where aircraft may descend below the glide path"],
    89: ["Provide an airborne collision-avoidance manoeuvre indication to the flight crew", "Provide traffic information only, without any manoeuvre guidance", "Provide ATC with an automatic separation instruction for the aircraft", "Provide a horizontal turn command to avoid conflicting traffic"],
    90: ["Respond to the RA in accordance with the applicable procedure", "Follow the ATC instruction, since it was issued first", "Request ATC confirmation before responding to the RA", "Follow the RA only if the conflicting aircraft is in sight"],
    91: ["Part-SPA", "Part-SPO", "Part-CAT", "Part-ORO"],
    92: ["Part-NCC", "Part-NCO", "Part-CAT", "Part-SPO"],
    93: ["Part-NCO", "Part-NCC", "Part-SPO", "Part-ORO"],
    94: ["Apply the approved contingency and minima; do not assume the approach is unchanged", "Continue the ILS to the original DA using the localiser only", "Continue descent on the last known glide path using timing", "Discontinue the procedure and descend visually to the runway"],
    95: ["Circling", "Holding", "Missed approach", "Straight-in approach"],
    96: ["To relate procedure design and minima to aircraft approach speed", "To relate procedure design and minima to aircraft wake-turbulence category", "To relate minima to the aircraft's maximum take-off mass only", "To relate the approach to the crew's licence and rating level"],
    97: ["Comply with both the procedure and the clearance, resolving any conflict with ATC", "The clearance always overrides the published procedure without discussion", "The published procedure always overrides any ATC clearance received", "Follow the procedure; ATC clearances are advisory on published routes"],
    98: ["Loss of obstacle clearance protection", "Loss of radio communication coverage", "Loss of wake-turbulence separation", "Loss of the ILS glide path signal"],
    99: ["ICAO Doc 8168 Volume I", "ICAO Doc 8168 Volume II", "ICAO Doc 4444", "ICAO Doc 9613"],
    100: ["ATC, FIS and Alerting Service", "ATC, FIS and Search and Rescue Service", "ATC, AIS and Alerting Service", "Area, approach and aerodrome control"],
    101: ["Promote safe, orderly and efficient air traffic and provide information and alerting", "Maximise airspace capacity and airport revenue for operators", "Provide separation only for commercial air transport flights", "Promote safe and orderly traffic and provide airline route licensing"],
    102: ["Area control, approach control and aerodrome control", "Area control, flight information and alerting service", "Area control, approach control and flight information", "En-route control, radar control and apron management"],
    103: ["Define an airspace region within which flight information and alerting services are provided", "Define airspace in which ATC separation is provided to all flights", "Define the region in which an RCC coordinates SAR only", "Define airspace in which only IFR flights are permitted"],
    104: ["Upper Flight Information Region", "Upper Information Route", "Upper Instrument Region", "Unified Information Region"],
    105: ["It determines the services, entry requirements and separation provided", "It determines the aircraft's airworthiness and registration requirements", "It determines only the minimum cruising altitude for each route", "It determines the navigation aids available along each route"],
    106: ["Ensure responsibility for control passes in a coordinated and defined manner", "Allow two units to control the aircraft at the same time for safety", "Reduce the pilot's radio workload by removing frequency changes", "Transfer responsibility for collision avoidance from the pilot to ATC"],
    107: ["Flight Information Service", "Alerting Service", "Air Traffic Control Service", "Aeronautical Information Service"],
    108: ["The ATS units designated as responsible under the airspace arrangements", "The Rescue Coordination Centre only, without ATS involvement", "The aircraft operator's flight dispatch office only", "The State of Registry of the aircraft concerned"],
    109: ["Required Navigation Performance", "Required Navigation Procedure", "Recommended Navigation Performance", "Radio Navigation Precision"],
    110: ["RNP is a navigation-performance specification; an ATS route is a defined route structure", "RNP is a defined route structure; an ATS route is a navigation-performance specification", "RNP and ATS routes are the same thing under different names", "RNP applies only to approaches; ATS routes apply only above FL245"],
    111: ["Authorise flight under specified conditions", "Guarantee terrain clearance for the whole flight", "Transfer PIC responsibility to the controller", "Provide advisory traffic information only"],
    112: ["The flight plan and the traffic situation, within ATC procedures", "The pilot's preferred route, regardless of the traffic situation", "The operator's schedule, which takes priority over other traffic", "The flight plan only, without regard to other traffic"],
    113: ["Safety-critical clearance elements such as route, level and heading", "Routine traffic information and weather observations", "Only the frequency change, since other items are optional", "ATIS information such as temperature and dew point"],
    114: ["To establish or maintain desired spacing and sequencing between aircraft", "To reduce fuel consumption for all aircraft in the sector", "To ensure each aircraft flies at its optimum cruise speed", "To provide vertical separation between aircraft on the same track"],
    115: ["In accordance with the applicable procedure, notifying ATC as required", "Only after landing, since IFR cannot be cancelled in flight", "At any time in VMC, without the need to inform ATC", "Only when ATC instructs the pilot to change to VFR"],
    116: ["Support separation and sequencing based on the wake hazard of each category", "Determine the runway length required by each aircraft", "Classify aircraft by approach speed for procedure minima", "Determine the noise category for night operations"],
    117: ["Uncertainty phase", "Alert phase", "Distress phase", "Emergency phase"],
    118: ["Alert phase", "Uncertainty phase", "Distress phase", "Alarm phase"],
    119: ["Distress phase", "Alert phase", "Uncertainty phase", "Danger phase"],
    120: ["INCERFA", "ALERFA", "DETRESFA", "MAYDAY"],
    121: ["Manage air traffic demand and capacity so traffic can be handled safely and efficiently", "Provide separation between individual aircraft in controlled airspace", "Allocate airline route licences between competing operators", "Provide flight information and alerting to all flights in an FIR"],
    122: ["ICAO Doc 4444", "ICAO Doc 8168", "ICAO Doc 7030", "ICAO Doc 9432"],
    123: ["Give ATS the aircraft's position and flight-progress information at required points", "Report weather observations only when requested by the MET office", "Replace the flight plan when the flight deviates from its route", "Notify the operator of the aircraft's estimated fuel remaining"],
    124: ["Significant operational or meteorological information required by the procedure", "Routine passenger and cargo load information for the operator", "Only the aircraft's position, without any weather information", "Maintenance defects to be passed to destination engineering"],
    125: ["Define where control responsibility passes from one ATC unit to the next", "Define where the aircraft must change from IFR to VFR", "Define where the pilot changes the altimeter setting to standard", "Define where the aircraft leaves the FIR and its SAR coverage"],
    126: ["Use the applicable PANS-ATM procedure and coordinate/notify ATC as required", "Cancel IFR by simply changing the transponder code to 7000", "Continue on the IFR clearance but fly visually without telling ATC", "Change to VFR only after leaving controlled airspace"],
    127: ["It depends on the ATS unit and procedure; the pilot must know the clearance's scope", "ATC is always responsible for terrain clearance once a clearance is issued", "ATC is never responsible for terrain clearance in any circumstance", "Terrain clearance is guaranteed by any clearance above the transition altitude"],
    128: ["Advise ATC promptly and request an alternative/clarification", "Comply anyway, as ATC holds responsibility for the outcome", "Disregard the clearance and continue on the flight plan route", "Comply partially and explain the deviation after landing"],
    129: ["Aerodrome control service", "Approach control service", "Area control service", "Flight information service"],
    130: ["Area control service", "Approach control service", "Aerodrome control service", "Alerting service"],
    131: ["Traffic in the vicinity of an aerodrome, within controlled airspace", "En-route traffic on airways between two aerodromes", "Military training areas adjacent to an aerodrome", "Traffic above FL245 in the upper airspace"],
    132: ["Recorded routine aerodrome information, reducing repetitive transmissions", "Individual ATC clearances for departing aircraft", "Live traffic information on all aircraft in the circuit", "Recorded en-route weather for all airways in the FIR"],
    133: ["To ensure aircraft receive current operational information relevant to safe flight", "To reduce the number of runway changes during the day", "To notify operators of passenger-related delays", "To replace the need for NOTAMs at the aerodrome"],
    134: ["Provide aeronautical information/data necessary for safe, regular and efficient air navigation", "Provide air traffic control and separation between aircraft", "Provide weather forecasts for all flights in the FIR", "Provide airline schedules and slot allocation information"],
    135: ["Provide aeronautical information of a lasting character essential to air navigation", "Provide aeronautical information of a temporary nature, such as short-term changes", "Provide time-critical information requiring immediate attention", "Provide pre-flight weather information for the planned flight"],
    136: ["GEN, ENR and AD", "GEN, AD and NOTAM", "ENR, AD and AIC", "GEN, ENR and SUP"],
    137: ["A permanent change to information in the AIP", "A temporary change to information in the AIP", "A time-critical change notified by NOTAM", "An advisory circular on administrative matters"],
    138: ["Temporary changes or temporary information published within the AIP structure", "Permanent changes to AIP information on AIRAC dates", "Time-critical information requiring immediate distribution", "Administrative or explanatory information not suited to the AIP"],
    139: ["It disseminates time-critical aeronautical information requiring prompt attention", "It publishes permanent information of a lasting character", "It provides explanatory and administrative advisory information", "It disseminates planned changes on a fixed 28-day cycle"],
    140: ["ASHTAM", "SNOWTAM", "BIRDTAM", "TAF"],
    141: ["SNOWTAM", "ASHTAM", "BIRDTAM", "AIC"],
    142: ["Planned promulgation of changes needing advance notice and common effective dates", "Immediate promulgation of unplanned changes requiring prompt attention", "Publication of temporary changes that last longer than three months", "Distribution of administrative circulars on non-operational matters"],
    143: ["Aeronautical Information Circular", "Aeronautical Information Chart", "Aerodrome Information Circular", "Air Information Communication"],
    144: ["Provide current aeronautical information relevant to the planned flight", "Provide the permanent AIP data for all aerodromes in the State", "Provide the ATC clearance for the planned flight", "Provide historical NOTAMs for statistical analysis"],
    145: ["NOTAM", "AIC", "AIP Amendment", "AIP Supplement"],
    146: ["AIP", "NOTAM", "AIC", "PIB"],
    147: ["Because planned changes may take effect and make current data or procedures invalid", "Because AIRAC changes are issued without notice and take effect immediately", "Because AIRAC only covers temporary information valid for one day", "Because AIRAC changes apply only to VFR charts, not databases"],
    148: ["AIS provides essential aeronautical information used in pre-flight preparation", "Pre-flight briefing is only required when AIS is unavailable", "AIS replaces the need for any weather information in the briefing", "Pre-flight briefing is the responsibility of ATC, not the pilot"],
    149: ["Relate aerodrome design characteristics to the aircraft intended to use it", "Relate pavement strength to aircraft mass for each movement", "Identify the aerodrome's location in the AIP and on charts", "Classify the aerodrome's rescue and firefighting category"],
    150: ["A defined geographic reference point for the aerodrome", "The highest point of the landing area", "The point where the ATC tower is located", "The threshold of the main instrument runway"],
    151: ["Pavement Classification Number", "Pavement Classification Rating", "Pavement Condition Number", "Pavement Capacity Number"],
    152: ["Aircraft Classification Number", "Aircraft Classification Rating", "Aircraft Category Number", "Aircraft Capacity Number"],
    153: ["The aircraft's loading effect (ACN) is compared with the pavement's capability (PCN)", "The pavement's capability (ACN) is compared with the aircraft's loading effect (PCN)", "The PCN is compared with the aircraft's approach speed category", "ACN and PCN are both measures of the runway length available"],
    154: ["Take-Off Run Available", "Take-Off Run Allowance", "Total Operational Runway Available", "Take-Off Rotation Area"],
    155: ["Take-Off Distance Available", "Take-Off Distance Assessed", "Take-Off Distance Actual", "Total Obstacle-free Distance Available"],
    156: ["Accelerate-Stop Distance Available", "Accelerate-Stop Distance Actual", "Approach-Stop Distance Available", "Aborted-Stop Distance Allowed"],
    157: ["Landing Distance Available", "Landing Distance Required", "Landing Distance Assessed", "Landing Descent Area"],
    158: ["It provides operationally significant information affecting aircraft movement and safety", "It is used only for pavement maintenance scheduling by the operator", "It is only relevant for aerodrome charging and landing fees", "It is only reported for runways, not for taxiways or aprons"],
    159: ["At the beginning of the runway portion declared usable for landing", "Always at the physical beginning of the paved runway surface", "At the point where the ILS glide path meets the runway", "At the end of the stopway, before the runway begins"],
    160: ["A defined area including the runway, reducing risk to aircraft running off it", "A paved area beyond the runway end for stopping in an abandoned take-off", "An area beyond the runway over which an aircraft may make its initial climb", "The painted centreline stripe used for guidance along the runway"],
    161: ["An area beyond the take-off run prepared for stopping in an abandoned take-off", "An area beyond the runway end over which the aircraft makes its initial climb", "An area before the threshold used to extend the landing distance available", "An area beside the runway used for holding before take-off"],
    162: ["An area beyond the runway end over which an aircraft may make part of its initial climb", "An area beyond the take-off run prepared for stopping in an abandoned take-off", "An area beside the runway kept free of obstacles for taxiing aircraft", "An area before the threshold in which aircraft may begin the landing flare"],
    163: ["Provide standard visual guidance and identification for safe surface movement", "Provide guidance only for aircraft on final approach", "Indicate pavement strength and permitted aircraft mass", "Replace ATC clearances for taxiing aircraft"],
    164: ["Annex 9", "Annex 17", "Annex 10", "Annex 14"],
    165: ["Speed cross-border movement of aircraft, crew, passengers and cargo while keeping required controls", "Remove all border controls for international passengers and cargo", "Protect civil aviation against acts of unlawful interference", "Harmonise airline fares and baggage allowances across borders"],
    166: ["Crew", "Air traffic controllers", "Maintenance engineers", "Aircraft manufacturers"],
    167: ["Entry and departure processing and documentation", "Aircraft weight and balance calculations", "Runway declared distances publication", "Holding and approach procedures"],
    168: ["Cargo entry, documentation and clearance requirements", "Cargo aircraft performance and loading limits", "Dangerous goods classification and packing", "Cargo hold fire-suppression requirements"],
    169: ["International operations depend on correct documentation and border processes", "Facilitation replaces the need for security screening", "Facilitation determines aircraft performance limits abroad", "Only the operator's ground staff are affected by facilitation"],
    170: ["Facilitation focuses on efficient processing; security focuses on protection against unlawful interference", "Facilitation focuses on protection against unlawful interference; security focuses on efficient processing", "Facilitation and security are identical and both covered by Annex 17", "Facilitation covers cargo only; security covers passengers only"],
    171: ["Because entry/departure processing includes crew identification and documentation", "Because crew members are exempt from all entry and departure formalities", "Because crew documents replace the aircraft's Certificate of Airworthiness", "Because Annex 9 sets flight-time limits for international crew"],
    172: ["Holding entry procedure", "Crew member certificates", "Passenger entry documents", "Cargo clearance procedures"],
    173: ["Resolve it through the operator or appropriate authority before the operation", "Operate the flight and resolve the issue on arrival", "Operate the flight if the missing document is not safety-related", "Obtain replacement documents from the destination ATC unit"],
    174: ["Annex 12", "Annex 13", "Annex 11", "Annex 10"],
    175: ["Rescue Coordination Centre", "Regional Control Centre", "Rescue Communication Centre", "Radar Control Centre"],
    176: ["A phase in which uncertainty exists regarding the safety of an aircraft and its occupants", "A phase in which apprehension exists regarding the safety of an aircraft and its occupants", "A phase in which there is reasonable certainty of grave and imminent danger", "A phase in which the aircraft is known to be subject to unlawful interference"],
    177: ["A phase in which apprehension exists regarding the safety of an aircraft and its occupants", "A phase in which uncertainty exists regarding the safety of an aircraft and its occupants", "A phase in which there is reasonable certainty of grave and imminent danger", "A phase declared once the aircraft's fuel is considered exhausted"],
    178: ["A phase with reasonable certainty of grave and imminent danger requiring immediate assistance", "A phase in which apprehension exists regarding the safety of an aircraft", "A phase in which uncertainty exists regarding the safety of an aircraft", "A phase in which an aircraft has failed to make one position report"],
    179: ["Coordinate SAR resources and actions within its area of responsibility", "Provide air traffic control to aircraft in distress", "Investigate the cause of the accident after the rescue", "Coordinate SAR resources worldwide regardless of region"],
    180: ["Follow SAR procedures, relay useful information and assist when practicable and safe", "Maintain radio silence and take no action unless requested by the RCC", "Divert immediately to the distress position regardless of fuel", "Take no action, as only ATC units may act on distress messages"],
    181: ["They provide a common way to communicate when radio is unavailable or ineffective", "They replace radio communication in all SAR operations", "They identify the aircraft's registration to rescue units", "They are only used to mark the landing area for helicopters"],
    182: ["Annex 17", "Annex 9", "Annex 18", "Annex 13"],
    183: ["Safeguard civil aviation against acts of unlawful interference", "Safeguard civil aviation against accidents caused by technical failure", "Speed the clearance of passengers and cargo across borders", "Investigate accidents to prevent their recurrence"],
    184: ["Screening", "Security audit", "Aircraft security search", "Background check"],
    185: ["An area where access is controlled for aviation security purposes", "An area where access is restricted for noise-abatement purposes", "An area of airspace where flight is restricted for military purposes", "An area of the apron where aircraft refuelling takes place"],
    186: ["Detect prohibited items or threats, as required by the security programme", "Verify the aircraft is airworthy before the first flight of the day", "Check that passengers' travel documents are valid for entry", "Confirm that cargo has been loaded within mass and balance limits"],
    187: ["An intentional act that threatens the security of civil aviation", "An unintentional act that endangers the safety of civil aviation", "Any breach of the Rules of the Air by a flight crew member", "Any disruptive passenger behaviour that does not affect safety"],
    188: ["Define the operator's security measures required by the State's security framework", "Define the operator's safety management and accident prevention policy", "Define the aircraft's minimum equipment list for dispatch", "Define the passenger facilitation and customs procedures"],
    189: ["Follow the unlawful-interference procedure unless conditions aboard dictate otherwise", "Comply with all demands without informing ATC by any means", "Land at the nearest aerodrome regardless of the situation on board", "Follow the procedure strictly, even if conditions aboard make it unsafe"],
    190: ["They are part of measures to protect the flight crew compartment against unlawful access", "They are required to reduce cabin noise on the flight deck", "They are designed mainly to protect the crew during turbulence", "They must remain open to allow cabin crew free access"],
    191: ["Safety addresses hazards/accident prevention; security addresses intentional unlawful acts", "Security addresses hazards/accident prevention; safety addresses intentional unlawful acts", "Safety and security are the same concept, both covered by Annex 17", "Safety applies to aircraft; security applies only to airports"],
    192: ["Annex 13", "Annex 12", "Annex 17", "Annex 19"],
    193: ["Prevent future accidents and incidents", "Apportion blame and liability", "Determine insurance compensation", "Prosecute those found responsible"],
    194: ["The State in whose territory the accident or incident occurs", "The State in which the aircraft is registered", "The State in which the operator is based", "The State in which the aircraft was designed"],
    195: ["The State in which the aircraft is registered", "The State in whose territory the accident occurs", "The State in which the operator is based", "The State in which the aircraft was manufactured"],
    196: ["An incident in which circumstances indicate that an accident nearly occurred", "An accident in which one or more persons are seriously injured", "Any incident that results in a flight delay of more than one hour", "An event involving damage that requires major repair of the aircraft"],
    197: ["Provide recorded information that can support factual reconstruction and safety analysis", "Provide evidence mainly used to prosecute the flight crew", "Record passenger announcements for the operator's records", "Provide real-time position data to ATC during flight"],
    198: ["The investigation is for prevention and lessons learned; enforcement is separate", "The investigation's main purpose is to support enforcement action", "The investigation and enforcement form one combined legal process", "Investigation findings are primarily used to assign criminal liability"],
    199: ["RCAB 22", "ICAO Annex 19", "ICAO Doc 9859", "TCAR OPS Part-ORO"],
    200: ["To make the difference known internationally so users can account for the State's implementation", "To obtain ICAO's approval before the State may deviate from the Standard", "To apply for a temporary exemption from the Chicago Convention", "To allow ICAO to impose penalties on the non-complying State"],
}


# Longer variants so the correct option is not reliably the longest one.
# id -> {option index in C[id] (0 = correct): replacement text}
LONGER = {
    19: {1: "It drafts ICAO Standards and Recommended Practices on behalf of the States in its region"},
    22: {2: "To certify that the operator holds a valid Air Operator Certificate for that aircraft"},
    27: {2: "It affects only the aircraft's registration status, not whether it may be operated"},
    28: {2: "The PIC may accept the damage and continue if the aircraft still handles normally in flight"},
    35: {1: "A separate licence issued for each aircraft category, such as an aeroplane or helicopter licence"},
    39: {1: "To permit flight in IMC outside controlled airspace without the need for an ATC clearance"},
    43: {1: "To demonstrate continued medical fitness for the privileges of the relevant licence and rating"},
    46: {1: "Continue exercising privileges until the next scheduled medical examination is due"},
    48: {2: "Because a rating can still be exercised on its own after the licence itself has lapsed"},
    51: {2: "To give larger, less manoeuvrable aircraft priority over smaller aircraft in all situations"},
    57: {1: "A VFR flight conducted outside controlled airspace at night without any flight plan or clearance"},
    58: {1: "An ATC IFR clearance substitutes for the instrument rating while the flight is under control"},
    59: {1: "To obtain an automatic departure slot and landing permission at the destination aerodrome"},
    64: {1: "They replace the need for a serviceable transponder when flying in controlled airspace at night"},
    65: {1: "Continue the flight as planned, since it was filed as VFR and the plan remains valid"},
    67: {3: "Because ATC separation is always provided between VFR and IFR traffic in all classes of airspace"},
    68: {1: "Right of way removes any need for the aircraft that has priority to watch for or avoid other traffic"},
    69: {1: "Continue to follow the clearance exactly as issued, since ATC is responsible for separating traffic"},
    70: {2: "To provide procedures for air traffic management, ATC clearances and separation between aircraft"},
    73: {1: "A departure that must follow one single published route from the runway to the first en-route fix"},
    75: {1: "Provide the most direct route from the arrival fix to the runway, without any obstacle protection"},
    79: {3: "It allows the crew to descend below the published minima to regain the required visual references"},
    83: {1: "They increase fuel burn and ATC workload but have no effect on the aircraft's obstacle clearance"},
    84: {1: "To guarantee terrain and obstacle clearance even when the aircraft is flown off the published procedure"},
    86: {2: "A surface of constant atmospheric pressure referenced to the local QNH setting"},
    89: {2: "Provide ATC with an automatic separation instruction to be relayed to the aircraft's flight crew"},
    94: {2: "Continue descent on the last known glide path using timing and DME distances down to the original DA"},
    97: {1: "The ATC clearance always overrides the published procedure, without any need to query a conflict"},
    101: {3: "Promote safe and orderly air traffic and provide airline route licensing and slot allocation"},
    103: {1: "Define an airspace region within which ATC separation service is provided to all IFR and VFR flights"},
    106: {1: "Allow two ATC units to share control of the aircraft at the same time to provide extra monitoring"},
    108: {1: "The Rescue Coordination Centre only, acting directly without any involvement of the ATS units"},
    113: {2: "Only the frequency change and squawk code, since other clearance items are optional to read back"},
    114: {3: "To provide vertical separation between aircraft following the same track at different levels"},
    115: {1: "Only after landing at the destination, since an IFR flight plan cannot be cancelled while airborne"},
    116: {2: "Classify aircraft according to approach speed so that procedure minima can be determined"},
    121: {1: "Provide tactical separation between individual aircraft operating within controlled airspace"},
    123: {1: "Report weather observations to ATS only when specifically requested by the meteorological office"},
    124: {1: "Routine passenger, cargo and fuel load information for the operator's flight dispatch office"},
    125: {3: "Define where the aircraft leaves the FIR and SAR responsibility passes to the adjacent region"},
    126: {2: "Continue on the IFR clearance but fly visually, without telling ATC that the flight is now VFR"},
    131: {1: "En-route traffic on the airway structure between two aerodromes, above the terminal area"},
    132: {3: "Recorded en-route weather and NOTAM information for all airways within the FIR"},
    133: {1: "To reduce the number of runway changes and ATC transmissions needed during the busy periods of the day"},
    134: {0: "Provide the aeronautical data needed for safe, regular and efficient air navigation",
          1: "Provide air traffic control, flight information and separation between aircraft in the FIR",
          3: "Provide airline schedules, slot allocations and airport charges information to operators"},
    138: {3: "Administrative or explanatory information that is not suited to publication in the AIP itself"},
    139: {1: "It publishes permanent aeronautical information of a lasting character essential to navigation"},
    142: {2: "Publication of temporary changes that last longer than three months or contain extensive graphics"},
    144: {1: "Provide the permanent AIP data and charts for every aerodrome within the State's territory"},
    147: {1: "Because AIRAC changes are issued without any prior notice and take effect immediately upon publication"},
    148: {2: "AIS replaces the need for any meteorological information to be obtained in the pre-flight briefing"},
    149: {1: "Relate pavement strength to the aircraft's mass so the aerodrome can accept each movement"},
    150: {3: "The threshold of the main instrument runway, used as the aerodrome's datum"},
    158: {1: "It is used only by the aerodrome operator for scheduling pavement maintenance and repair work"},
    162: {2: "An area beside the runway kept free of obstacles and graded for aircraft that are taxiing past it"},
    163: {1: "Provide lighting and guidance only for aircraft on final approach to the runway threshold"},
    165: {1: "Remove border controls so that international passengers, baggage and cargo move without any formalities"},
    167: {1: "Aircraft weight and balance calculations and loading documentation"},
    168: {1: "Cargo aircraft performance, loading limits and documentation for the load sheet"},
    169: {3: "Only the operator's ground handling staff are affected by facilitation, not the flight crew"},
    173: {2: "Operate the flight anyway if the missing document is not considered to be safety-related"},
    178: {0: "A phase in which there is reasonable certainty of grave and imminent danger",
          1: "A phase in which apprehension exists regarding the safety of an aircraft and its occupants",
          2: "A phase in which uncertainty exists regarding the safety of an aircraft and its occupants"},
    179: {3: "Coordinate SAR resources worldwide, regardless of which region the aircraft was lost in"},
    180: {1: "Maintain radio silence and take no action at all unless specifically requested to by the RCC"},
    181: {1: "They replace radio communication entirely in all SAR operations, even when radio is available"},
    186: {1: "Verify that the aircraft is airworthy and correctly configured before the first flight of the day"},
    188: {1: "Define the operator's safety management system and its accident prevention policy and procedures"},
    189: {3: "Follow the published procedure strictly in all cases, even if conditions aboard make it unsafe"},
    190: {2: "They are designed mainly to protect the flight crew from injury caused by severe turbulence or decompression"},
    194: {2: "The State in which the operator has its principal place of business"},
    196: {3: "An event involving damage to the aircraft that requires major repair before further flight"},
    197: {1: "Provide evidence mainly intended to support prosecution of the flight crew after an accident"},
    198: {3: "Investigation findings are primarily used to assign criminal and civil liability to individuals"},
    200: {0: "To make the difference known so other States and users can account for it",
          1: "To obtain ICAO's formal approval before the State is permitted to deviate from the Standard"},
}

for _id, _edits in LONGER.items():
    for _i, _text in _edits.items():
        C[_id][_i] = _text


def main():
    qs = json.loads(BANK.read_text())
    assert len(C) == len(qs) == 200
    rng = random.Random(10)
    letters = list("ABCD" * (len(qs) // 4))
    rng.shuffle(letters)
    for q, letter in zip(qs, letters):
        opts = C[q["id"]]
        assert len(opts) == 4 and len(set(opts)) == 4, q["id"]
        correct, wrong = opts[0], opts[1:]
        rng.shuffle(wrong)
        idx = "ABCD".index(letter)
        q["choices"] = wrong[:idx] + [correct] + wrong[idx:]
        q["answer"] = letter
        if q["id"] in QUESTION_EDITS:
            q["question"] = QUESTION_EDITS[q["id"]]
    BANK.write_text(json.dumps(qs, indent=2, ensure_ascii=False) + "\n")


if __name__ == "__main__":
    main()
