"""Replace the wrong options in the Air Law bank with closer, plausible distractors.

The correct option text and its position (answer index) are never changed.
Distractors come from NEW below, or from the matching entry in rewrite_choices.C
when the correct answer text is identical.

Usage: python3 scripts/rewrite_distractors.py
"""
import json
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from rewrite_choices import C  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
BANK = ROOT / "data" / "010_air_law_question_bank.json"

NEW = {
    1: ["Paris Convention", "Warsaw Convention", "Tokyo Convention"],
    28: ["The aircraft's continued airworthiness may be assumed until the next scheduled inspection",
         "The aircraft's registration must be reassessed and a new registration mark issued before flight",
         "The PIC may accept the damage and continue if the aircraft still handles normally in flight"],
    29: ["Annex 8 - nationality and registration marks",
         "Annex 7 - airworthiness of aircraft",
         "Annex 1 - rules of the air"],
    31: ["TCAR PEL provides international standards; Annex 1 provides the applicable national licensing framework",
         "Annex 1 provides binding national rules; TCAR PEL provides only non-binding guidance for licensing",
         "Annex 1 applies only to ATPL holders; TCAR PEL applies to the PPL and CPL licensing framework"],
    35: ["A privilege/qualification attached to a licence, such as a PPL, CPL or ATPL licence",
         "A medical assessment attached to a licence, such as a Class 1 or Class 2 medical certificate",
         "A separate licence issued for each aircraft category, such as an aeroplane or helicopter licence"],
    36: ["ATPL", "PPL", "MPL"],
    39: ["To provide the applicable pilot qualification for VFR/night operations within its privileges",
         "To permit flight in IMC outside controlled airspace without the need for an ATC clearance",
         "To replace the need for a type rating when operating complex aircraft under IFR"],
    44: ["Renewal continues validity before expiry; revalidation restores a privilege/rating after expiry under applicable requirements",
         "Revalidation and renewal are identical terms, both used to extend a privilege/rating before it expires",
         "Revalidation applies only to licences; renewal applies only to medical certificates after expiry"],
    46: ["Continue exercising privileges until the next scheduled medical examination confirms the decrease",
         "Continue exercising privileges provided a second qualified pilot is on board for every flight",
         "Follow the applicable medical regulation but continue to exercise privileges until the licence expires"],
    48: ["Because the ability to exercise a privilege depends only on the licence, not on ratings or conditions",
         "Because holding the licence automatically includes every rating needed for the aircraft flown",
         "Because a rating can still be exercised on its own after the licence itself has lapsed"],
    51: ["To reduce ATC workload by transferring all collision-avoidance responsibility to the flight crew",
         "To give ATC sole responsibility for separating all traffic through standardised clearances",
         "To give larger, less manoeuvrable aircraft priority over smaller aircraft in all situations"],
    52: ["Each should alter heading to the left, subject to the applicable rule",
         "The aircraft on the left should give way by climbing, subject to the applicable rule",
         "The faster aircraft should alter heading to the right; the slower maintains heading"],
    55: ["Maintain responsibility for navigation only, while ATC assumes responsibility for collision avoidance",
         "Transfer responsibility for the safe operation of the flight to ATC while under positive control",
         "Follow ATC instructions only, since separation is no longer the PIC's responsibility under ATC"],
    56: ["Operation in accordance with applicable instrument meteorological conditions and VFR requirements",
         "Operation above any cloud layer at all times, with the ground visible at the departure point",
         "Operation with an instrument rating whenever visibility falls below VFR requirements"],
    57: ["A VFR flight conducted outside controlled airspace without any clearance or conditions",
         "An IFR flight that is cleared to proceed visually to the runway subject to conditions",
         "A special VFR operation conducted at night above the transition altitude without a clearance"],
    58: ["An ATC IFR clearance substitutes for the instrument rating while the flight is under control",
         "The pilot must meet the applicable qualification for IFR only when flying in Class A airspace",
         "A CPL alone permits IFR flight without any further rating once the IFR flight plan is filed"],
    59: ["To provide the information needed for flight crew licensing, flight time logging and medical records",
         "To obtain an automatic departure slot and landing permission at the destination aerodrome",
         "To replace the need for a pre-flight weather and NOTAM briefing before departure"],
    61: ["Traffic information authorises/permits an operation within specified conditions; a clearance provides useful information but is not an authorisation",
         "A clearance transfers collision-avoidance responsibility to ATC; traffic information leaves that responsibility with the pilot",
         "Both authorise/permit an operation within specified conditions and carry exactly the same legal effect"],
    64: ["They help identify aircraft and relative position during operations, but are required only in daylight conditions",
         "They replace the need for a serviceable transponder when flying in controlled airspace at night",
         "They indicate the aircraft's State of Registry and operator to other traffic during night operations"],
    65: ["The pilot may continue under VFR in IMC, provided the flight plan was originally filed as VFR",
         "The pilot must switch to IFR immediately without contacting ATC or following any published procedure",
         "An ATC clearance automatically converts the flight to IFR once the pilot reports being in IMC"],
    67: ["Because ATC is legally liable for any collision in controlled airspace, not the pilot",
         "Because pilots only need collision-avoidance rules when ATC service fails or radio contact is lost",
         "Because ATC separation is always provided between VFR and IFR traffic in all classes of airspace"],
    73: ["A departure procedure designed so the aircraft must follow a single fixed departure route to the first en-route fix rather than any other track/direction",
         "A departure procedure designed so the aircraft can depart visually in any direction without any published obstacle-clearance criteria",
         "A departure procedure designed so the aircraft departs on radar vectors only, with tracks/directions assigned by ATC after take-off"],
    75: ["Provide the most direct route from the arrival environment toward the runway without any obstacle-clearance protection",
         "Provide a structured route and separation framework between departing aircraft leaving the runway environment",
         "Provide a structured route for taxiing from the runway exit toward the parking stand/apron reference"],
    80: ["Continue descent on the approach until the required visual references are acquired",
         "Level off at the minimum altitude and continue toward the runway threshold as applicable",
         "Initiate a visual circling manoeuvre to locate the runway before landing"],
    81: ["To provide a defined pattern for descending below the MDA while awaiting the required visual reference",
         "To provide a fuel-saving cruise pattern for aircraft during the en-route phase of flight",
         "To provide a defined pattern for delaying aircraft, without any obstacle-clearance protection being assured"],
    84: ["To guarantee terrain and obstacle clearance even when the aircraft is flown off the published procedure",
         "To provide defined separation margins between aircraft following the same procedure",
         "To provide defined margins from noise-sensitive areas for aircraft on the procedure"],
    85: ["A pressure setting used to reference height to the aerodrome elevation under the applicable standard",
         "A standard pressure setting of 1013.25 hPa used to indicate flight levels above the transition altitude",
         "A pressure setting used to reference altitude to mean sea level corrected for temperature in all conditions"],
    86: ["A surface of constant atmospheric pressure referenced to the local QNH setting",
         "A surface of constant altitude referenced to mean sea level under standard conditions",
         "A surface of constant height referenced to the aerodrome elevation"],
    94: ["Continue the ILS using the localiser only and apply the original precision minima without any change to the procedure",
         "Continue descent on the last known glide path using timing and DME distances down to the original DA/H",
         "Apply the procedure's published contingency, but descend below minima if necessary to regain the glide path signal"],
    96: ["To relate procedure design/minima to aircraft wake-turbulence characteristics as specified by the procedure",
         "To relate minima to the aircraft's maximum certificated take-off mass only",
         "To relate the approach procedure to the crew's licence and rating level"],
    97: ["The ATC clearance always overrides the published procedure, so the pilot need not query any conflict before proceeding",
         "The published procedure always overrides any ATC clearance, so the pilot should disregard conflicting instructions",
         "The pilot must comply with the published procedure only; ATC clearances are advisory once established on a published route"],
    101: ["Promote safe, orderly and efficient conduct of air traffic and provide airline route licensing and slot allocation",
          "Maximise airspace capacity and airport revenue for operators, while providing alerting functions only on request",
          "Provide separation only for commercial air transport flights and required information to those flights"],
    105: ["It determines the applicable aircraft airworthiness, registration and equipment requirements",
          "It determines only the minimum cruising altitude and navigation aids available on each route",
          "It determines the applicable ATS/ATC services, but separation is provided identically in all classes"],
    108: ["The Rescue Coordination Centre only, acting directly without any involvement of the ATS units",
          "The aircraft operator's flight dispatch office responsible for the flight under its AOC",
          "The State of Registry of the aircraft, regardless of the airspace in which it is operating"],
    111: ["Guarantee terrain clearance for a flight or portion of flight under all conditions",
          "Transfer responsibility for the safe conduct of the flight from the PIC to the controller",
          "Advise a flight of traffic information without authorising it to proceed"],
    112: ["The pilot's preferred route and requested level, regardless of the traffic/operational situation",
          "The operator's published schedule, which takes priority over the traffic situation within the ATC system",
          "The applicable flight plan only, without regard to the traffic/operational situation"],
    113: ["Routine traffic information, weather observations and other non-safety-critical advisory items",
          "Only the frequency change and squawk code, since other clearance elements are optional to read back",
          "ATIS information such as temperature, dew point and cloud observations from the recorded broadcast"],
    115: ["Only after landing at destination, since an IFR flight plan cannot be cancelled while airborne",
          "At any time in VMC, without any request/notification to ATC, simply by changing the transponder code",
          "Only when ATC instructs the pilot to change to VFR, regardless of the applicable procedure"],
    116: ["Support separation and sequencing based on the approach speed associated with aircraft categories",
          "Determine the runway length and pavement strength required by each aircraft category",
          "Determine the noise category and permitted night operating hours for each aircraft"],
    121: ["Provide tactical separation between individual aircraft so that traffic can be handled safely",
          "Allocate airline route licences between competing operators according to demand and capacity",
          "Provide flight information and alerting services to all flights operating within an FIR"],
    123: ["Provide the operator with the aircraft's fuel state and passenger information at required points",
          "Report weather observations to ATS only when specifically requested by the meteorological office",
          "Replace the flight plan when the flight deviates from its route, without further coordination"],
    124: ["Routine passenger, cargo and fuel load information required by the operator's flight dispatch",
          "Only the aircraft's position and level, without any operational or meteorological information",
          "Maintenance defects and technical log entries to be passed to the destination engineering"],
    125: ["Define where the aircraft must change from IFR to VFR under coordinated procedures",
          "Define where the pilot changes the altimeter setting from QNH to standard pressure",
          "Define where SAR responsibility is transferred between Rescue Coordination Centres under coordinated procedures"],
    127: ["Every ATC clearance guarantees terrain clearance regardless of the type of ATS unit, so the pilot need not understand the clearance's scope",
          "No ATC unit can ever provide terrain-related protection, whatever the type of ATS unit or applicable procedure",
          "Terrain clearance is guaranteed by any ATC clearance once the aircraft is above the transition altitude"],
    131: ["En-route traffic on the airway structure between two aerodromes, above the terminal control area",
          "Traffic in upper airspace above FL245 within the applicable controlled airspace structure",
          "Military training traffic in the vicinity of an aerodrome within uncontrolled airspace"],
    132: ["Recorded en-route weather and NOTAM information for all airways within the FIR to reduce briefing time",
          "Individual ATC clearances for departing aircraft to reduce repetitive transmissions on the ground frequency",
          "Live traffic information on all aircraft in the circuit to improve situational awareness"],
    134: ["Provide air traffic control, flight information and separation between aircraft in the FIR",
          "Provide aeronautical meteorological forecasts necessary for safe, regular and efficient air navigation",
          "Provide airline schedules, slot allocations and airport charges information to operators"],
    138: ["Permanent changes to AIP information that are published on AIRAC effective dates",
          "Time-critical information of a temporary nature that requires immediate distribution by NOTAM",
          "Administrative or explanatory information of a lasting nature that is not suited to the AIP structure"],
    142: ["Immediate promulgation of unplanned aeronautical information changes that require prompt attention by NOTAM",
          "Publication of temporary aeronautical information changes that last longer than three months, with extensive graphics",
          "Distribution of administrative and explanatory circulars on non-operational matters"],
    147: ["Because AIRAC changes are issued without any prior notice and take effect immediately upon publication",
          "Because AIRAC only covers temporary information that remains valid for a single day of operations",
          "Because AIRAC changes apply only to VFR charts and never affect navigation database information"],
    148: ["AIS replaces the need for any meteorological information to be obtained in the pre-flight briefing",
          "Pre-flight briefing is only required when AIS information is unavailable for the planned flight",
          "Pre-flight briefing is the responsibility of ATC, which provides AIS information on the frequency"],
    149: ["Relate pavement strength to aircraft mass so the aerodrome can accept each aircraft movement",
          "Identify the aerodrome's location and ICAO indicator for use in the AIP and on charts",
          "Classify the aerodrome's rescue and firefighting category according to aircraft characteristics"],
    153: ["Pavement capability (ACN) is compared with the aircraft loading/strength effects represented by PCN under the applicable system",
          "The PCN is compared with the aircraft's approach speed category to determine permitted runway use",
          "ACN and PCN are both measures of the runway length available, compared under the applicable system"],
    159: ["At the physical beginning of the paved runway surface in all cases, including any stopway",
          "At the point where the ILS glide path intersects the runway, subject to applicable criteria",
          "At the end of the portion of runway declared suitable for landing, subject to applicable criteria"],
    160: ["A paved area beyond the runway end prepared for stopping an aircraft in an abandoned take-off, as applicable",
          "An area beyond the runway end over which an aircraft may make part of its initial climb, subject to criteria",
          "An area including the runway and associated taxiways intended to reduce risk of collision between taxiing aircraft and support ground operations"],
    161: ["An area beyond the runway end prepared as an available area over which an aircraft may make part of its initial climb",
          "An area before the threshold designed and prepared to extend the landing distance available, as applicable",
          "An area beyond the take-off run designed and prepared for aircraft to hold before take-off, as applicable"],
    162: ["An area beyond the take-off run designed and prepared for stopping an aircraft in an abandoned take-off, as applicable",
          "An area beside the runway kept free of obstacles and prepared for aircraft taxiing past the runway, subject to criteria",
          "An area before the threshold prepared as an available area over which an aircraft may begin its landing flare"],
    165: ["Remove border controls entirely so that aircraft, crew, passengers, baggage and cargo move without any formalities",
          "Protect aircraft, crew, passengers, baggage and cargo against acts of unlawful interference across borders",
          "Harmonise airline fares, baggage allowances and cargo charges across borders while maintaining required controls"],
    169: ["International operations depend on correct aircraft performance data and runway strength at each foreign aerodrome",
          "Facilitation replaces the need for security screening of crew, passengers, baggage and cargo at border points",
          "Facilitation determines the ATC routes and clearances required for international operations"],
    171: ["Because international entry/departure processing exempts crew from identification and documentation requirements",
          "Because crew documentation replaces the aircraft's Certificate of Airworthiness on international flights",
          "Because Annex 9 sets the flight-time and duty limits for crew on international flights"],
    173: ["Conduct the operation as planned and resolve the documentation issue with the authority on arrival",
          "Conduct the operation, since an ATC clearance replaces the need for the missing international documentation",
          "Resolve the documentation issue only if the missing document is considered safety-related"],
    178: ["A phase in which apprehension exists regarding the safety of an aircraft and its occupants",
          "A phase in which uncertainty exists regarding the safety of an aircraft and its occupants",
          "A phase in which there is reasonable certainty that the aircraft has landed safely at an alternate aerodrome"],
    180: ["Maintain radio silence and take no action at all unless specifically requested to by the RCC",
          "Divert immediately to the distress position regardless of fuel state or the safety of the flight",
          "Take no action, since only designated SAR aircraft and ATC units may respond to distress messages"],
    181: ["They replace radio communication entirely in all SAR operations, even when radio is available",
          "They identify the aircraft's registration and operator to rescue units when radio is unavailable",
          "They are only used to mark the landing area for SAR helicopters when normal lighting is ineffective"],
    186: ["Verify that the aircraft is airworthy and correctly configured before the first flight of the day",
          "Check that passengers' travel documents are valid for entry in accordance with the applicable procedure",
          "Confirm that cargo and baggage have been loaded within the mass and balance limits of the aircraft"],
    188: ["Define the operator's safety management system and accident prevention procedures required by the State",
          "Define the aircraft's minimum equipment list and dispatch procedures required by the State of the Operator",
          "Define the passenger facilitation and customs procedures required by the applicable State framework"],
    189: ["Follow the applicable unlawful-interference procedure strictly in all cases, even if conditions aboard make it unsafe",
          "Comply with all demands and avoid informing ATC by any means until the aircraft has landed safely",
          "Land at the nearest aerodrome immediately, regardless of the situation aboard the aircraft"],
    196: ["An accident involving circumstances in which one or more persons suffered serious or fatal injury",
          "An incident involving circumstances that caused a flight delay of more than one hour at departure",
          "An event involving damage to the aircraft that requires major repair or replacement before further flight"],
    198: ["The Annex 13 investigation is primarily for enforcement and assigning blame, while safety prevention is a separate process",
          "The Annex 13 investigation and enforcement form one combined legal process that apportions liability",
          "Investigation findings are primarily used to assign criminal and civil liability to individuals"],
    200: ["To obtain ICAO's formal approval before the State is permitted to deviate from the Standard",
          "To apply for a temporary exemption from the Chicago Convention until the Standard can be met",
          "To allow ICAO to impose penalties on the non-complying State until the difference is resolved"],
}


def distractors_for(q):
    if q["id"] in NEW:
        return list(NEW[q["id"]])
    reference = C.get(q["id"])
    if reference and reference[0] == q["options"][q["answer"]]:
        return list(reference[1:])
    raise SystemExit(f"No distractors for question {q['id']}: {q['correct']!r}")


def main():
    qs = json.loads(BANK.read_text())
    rng = random.Random(2026)
    for q in qs:
        correct = q["options"][q["answer"]]
        wrong = distractors_for(q)
        assert len(wrong) == 3 and len({correct, *wrong}) == 4, q["id"]
        rng.shuffle(wrong)
        q["options"] = wrong[: q["answer"]] + [correct] + wrong[q["answer"]:]
        assert q["options"][q["answer"]] == correct
    BANK.write_text(json.dumps(qs, indent=2, ensure_ascii=False) + "\n")
    print(f"Updated {len(qs)} questions")


if __name__ == "__main__":
    main()
